### ISSUE TITLE
debian 11 error

### ISSUE THREAD

**Issue by klein-de** [DexcTrack/dexctrack#12]
hi 
i tried to run your software on debian 11 crunchbang++11.
install seemed to go fine.
first run w/o meter connected software opened fine , i closed window and tried it with meter connected :

python3 dexctrack.py
DexcTrack  Copyright (C) 2018  Steve Erlenborn
This program comes with ABSOLUTELY NO WARRANTY.

(dexctrack.py:50218): Gtk-WARNING **: 18:39:03.274: Theme parsing error: gtk.css:2446:18: '-gtk-icon-filter' is not a valid property name

(dexctrack.py:50218): Gtk-WARNING **: 18:39:03.289: Theme parsing error: gtk.css:6264:18: '-gtk-icon-filter' is not a valid property name
Fatal Python error: Segmentation fault

Thread 0x00007face7fff700 (most recent call first):
  File "/home/klein/dexctrack/readReceiver.py", line 189 in DownloadToDb
  File "/home/klein/dexctrack/dexctrack.py", line 938 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap

Thread 0x00007face7757700 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 316 in wait
  File "/usr/lib/python3.9/threading.py", line 574 in wait
  File "/home/klein/dexctrack/dexctrack.py", line 1110 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap

Current thread 0x00007facf52e9740 (most recent call first):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 201 in draw_text
  File "/usr/lib/python3/dist-packages/matplotlib/text.py", line 727 in draw
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 41 in draw_wrapper
  File "/usr/lib/python3/dist-packages/matplotlib/image.py", line 131 in _draw_list_compositing_images
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 1863 in draw
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 41 in draw_wrapper
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 407 in draw
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 9 in draw
  File "/usr/lib/python3/dist-packages/matplotlib/widgets.py", line 873 in stop_typing
  File "/usr/lib/python3/dist-packages/matplotlib/widgets.py", line 905 in _resize
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 224 in process
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 1767 in resize_event
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_tk.py", line 241 in resize
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892 in __call__
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1429 in mainloop
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_tk.py", line 916 in mainloop
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 3544 in show
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 353 in show
  File "/home/klein/dexctrack/dexctrack.py", line 4272 in <module>
Segmentation fault

then i ran it with -d

 python3 dexctrack.py -d
DexcTrack  Copyright (C) 2018  Steve Erlenborn
This program comes with ABSOLUTELY NO WARRANTY.

(dexctrack.py:50228): Gtk-WARNING **: 18:39:21.729: Theme parsing error: gtk.css:2446:18: '-gtk-icon-filter' is not a valid property name

(dexctrack.py:50228): Gtk-WARNING **: 18:39:21.745: Theme parsing error: gtk.css:6264:18: '-gtk-icon-filter' is not a valid property name
get_screen_size width = 1440 , get_screen_size height = 900 , dispRatio = 1.6
sys.platform = linux
backend = TkAgg
matplotlib version = 3.3.4
sqlite_file = /home/klein/dexc_MX14106746.sqlite
rcParams[timezone] = America/New_York
Traceback (most recent call last):
  File "/home/klein/dexctrack/dexctrack.py", line 4269, in <module>
    plotGraph()
  File "/home/klein/dexctrack/dexctrack.py", line 3582, in plotGraph
    calcStats()
  File "/home/klein/dexctrack/dexctrack.py", line 2331, in calcStats
    curs.execute(selectSql, (ninetyDaysBack, displayEndSecs))
sqlite3.OperationalError: no such table: EgvRecord
*****************
Close in progress
*****************
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/_pylab_helpers.py", line 87, in destroy_all
    manager.destroy()
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_tk.py", line 467, in destroy
    self.window.destroy()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2312, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed

**Comment by DexcTrack** [comment]
Hi,

I think the critical line is: "sqlite3.OperationalError: no such table: EgvRecord"
That's a very strange error. It's possible that there is some problem reading data from your Receiver device. To test this, please run:

> python3 readdata.py

Here's an example of what this does on my system:

> ~/dexctrack(master)$ python3 readdata.py
> Firmware.ProductId = OrionReceiver
> Found Dexcom Orion Receiver S/N: PL75130020
> Transmitter paired: b'8N20A0'
> Battery Status: CHARGING (100%)
> Record count:
> - Meter records: 111
> - CGM records: 8759
> - CGM commitable records: 8759
> - Event records: 616
> - Insertion records: 36
> - Calibration records: 0
> - User Setting Records: 244

In my case, there are 8579 glucose readings found on my device. In normal operation, each of those are written to a EgvRecord in the SQLite database. I'd like to see if it finds any on yours. If I disconnect my device from the USB cable, and then run it again ...

> ~/dexctrack(master)$ python3 readdata.py
> Could not find Dexcom Receiver!

If you see that, check your USB cable conectivity and your user permissions on access to a USB connected device.

While waiting on your results, I'll download debian 11 crunchbang++11 and try installing it into a Virtualbox virtual machine. Maybe there's something extra needed in your OS to allow access to a USB device?

**Comment by klein-de** [comment]
python3 readdata.py
Firmware.ProductId = OrionReceiver
Found Dexcom Orion Receiver S/N: MX14106746
Transmitter paired: b'8XHGR1'
Battery Status: CHARGING (100%)
Record count:
- Meter records: 0
- CGM records: 2861
- CGM commitable records: 2861
- Event records: 28
- Insertion records: 5
- Calibration records: 0
- User Setting Records: 54

**Comment by klein-de** [comment]
sudo apt-get install python3 python3-pip python3-tk
[sudo] password for klein: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (20.3.4-4+deb11u1).
python3 is already the newest version (3.9.2-3).
python3-tk is already the newest version (3.9.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

sudo apt-get install git
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.30.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

git clone https://github.com/DexcTrack/dexctrack.git
Cloning into 'dexctrack'...
remote: Enumerating objects: 570, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 570 (delta 78), reused 108 (delta 69), pack-reused 448
Receiving objects: 100% (570/570), 325.68 KiB | 807.00 KiB/s, done.
Resolving deltas: 100% (376/376), done.


sudo pip3 install --upgrade setuptools
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (65.3.0)
Collecting setuptools
  Using cached setuptools-65.3.0-py3-none-any.whl (1.2 MB)
  Downloading setuptools-65.2.0-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 1.2 MB/s 

sudo pip3 install matplotlib pyserial pytz tzlocal numpy pympler
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (3.3.4)
Requirement already satisfied: pyserial in /usr/local/lib/python3.9/dist-packages (3.5)
Requirement already satisfied: pytz in /usr/local/lib/python3.9/dist-packages (2022.2.1)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.9/dist-packages (4.2)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.19.5)
Requirement already satisfied: pympler in /usr/local/lib/python3.9/dist-packages (1.0.1)
Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.9/dist-packages (from tzlocal) (0.1.0.post0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.9/dist-packages (from pytz-deprecation-shim->tzlocal) (2022.2)

sudo addgroup klein dialout
The user `klein' is already a member of `dialout'.

sudo cp dexctrack/etc/udev/rules.d/80-dexcom.rules /etc/udev/rules.d/

sudo udevadm control --reload-rules

**Comment by klein-de** [comment]
ok i figured it out, i had to delete the dexc_MX14106746.sqlite file and with the dexcom plunged in, and restart the software

**Comment by DexcTrack** [comment]
Great to hear you got it working! It was clear from your run of readdata.py that communication with the Receiver was working fine. Somehow you ended up with a
dexc_MX14106746.sqlite file which was damaged such that the EgvRecord table was missing. I'm not clear on how that could have happened.

**Comment by klein-de** [comment]
ghost in the machine is there a way to change dexc_MX14106746.sqlite into a lebraoffice chart ?

**Comment by DexcTrack** [comment]
You could install sqlitebrowser and use it to open dexc_MX14106746.sqlite, but first exit from dexctrack.py, for safety. In sqlitebrowser, you can click on the EgvRecord table, and then under the Browse Data tab you can see the entries. You can export data in some ways which might go into libreoffice. Keep in mind that sysSeconds time is stored in seconds since UTC_BASE_TIME (1/1/2009 00:00:00). Avoid using dispSeconds which is similar but in local time, which gets affected by daylight savings adjustments and time zone. It's always best to work in UTC time, and only adjust to local time for user display.

You might be able to use ODBC, as documented on this web site.
[https://wiki.openoffice.org/wiki/Documentation/How_Tos/Using_SQLite_With_OpenOffice.org
](url)

**Comment by DexcTrack** [comment]
I've merged in an update which will prevent a crash in calcStats() due to a database missing an EgvRecord table. I was able to recreate your failure scenario by removing my database, and then using 'touch <dbname>' to create an empty database file. With my fix, this no longer causes a crash, and the database gets fixed as the program continues.
You can pull in this update by using **git pull origin master**
